[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["no-std"]
description = "libm in pure Rust"
documentation = "https://docs.rs/libm"
keywords = ["libm", "math"]
license = "MIT AND (MIT OR Apache-2.0)"
name = "libm"
readme = "README.md"
repository = "https://github.com/rust-lang/libm"
version = "0.2.11"
edition = "2021"
exclude = ["/ci/", "/.github/workflows/"]
rust-version = "1.63"

[features]
default = ["arch"]

# Enable architecture-specific features such as SIMD or assembly routines.
arch = []

# This tells the compiler to assume that a Nightly toolchain is being used and
# that it should activate any useful Nightly things accordingly.
unstable = ["unstable-intrinsics"]

# Enable calls to functions in `core::intrinsics`
unstable-intrinsics = []

# Make some internal things public for testing.
unstable-test-support = []

# Used to prevent using any intrinsics or arch-specific code.
#
# HACK: this is a negative feature which is generally a bad idea in Cargo, but
# we need it to be able to forbid other features when this crate is used in
# Rust dependencies. Setting this overrides all features that may enable
# hard float operations.
force-soft-floats = []

[workspace]
resolver = "2"
members = [
  "crates/compiler-builtins-smoke-test",
  "crates/libm-macros",
  "crates/libm-test",
  "crates/musl-math-sys",
]
default-members = [
  ".",
  "crates/libm-macros",
  "crates/libm-test",
]

[dev-dependencies]
no-panic = "0.1.30"


# This is needed for no-panic to correctly detect the lack of panics
[profile.release]
lto = "fat"
