[package]
name = "util"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["build-musl", "build-mpfr", "unstable-float"]
build-musl = ["libm-test/build-musl", "dep:musl-math-sys"]
build-mpfr = ["libm-test/build-mpfr", "dep:az", "dep:rug"]
unstable-float = ["libm/unstable-float", "libm-test/unstable-float", "rug?/nightly-float"]

[dependencies]
az = { version = "1.2.1", optional = true }
libm = { path = "../..", default-features = false }
libm-macros = { path = "../libm-macros" }
libm-test = { path = "../libm-test", default-features = false }
musl-math-sys = { path = "../musl-math-sys", optional = true }
rug = { git = "https://gitlab.com/tspiteri/rug.git", rev = "2d96613fc1d84882b8651e86232fbb54ebe7c4c3", optional = true, default-features = false, features = ["float", "integer", "std"] }
