[package]
name = "cb"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2021"
publish = false

[lib]
test = false
bench = false

[features]
# Duplicated from libm's Cargo.toml
unstable = []
unstable-intrinsics = []
unstable-test-support = []
checked = []
force-soft-floats = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  "cfg(arch_enabled)",
  "cfg(assert_no_panic)",
  "cfg(f128_enabled)",
  "cfg(f16_enabled)",
  "cfg(intrinsics_enabled)",
] }
