[package]
name = "cb"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]
test = false
bench = false

[features]
default = ["arch", "compiler-builtins", "unstable-float"]

# Copied from `libm`'s root `Cargo.toml`'
arch = []
compiler-builtins = []
unstable-float = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  "cfg(arch_enabled)",
  "cfg(assert_no_panic)",
  "cfg(intrinsics_enabled)",
  'cfg(feature, values("force-soft-floats"))',
  'cfg(feature, values("unstable"))',
  'cfg(feature, values("unstable-intrinsics"))',
  'cfg(feature, values("unstable-public-internals"))',
] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
